"""rename department

Revision ID: dcc0f612366f
Revises: 32dcdc0678aa
Create Date: 2024-07-10 02:31:36.427120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc0f612366f'
down_revision = '32dcdc0678aa'
branch_labels = None
depends_on = None


def upgrade():
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###
