"""rename address

Revision ID: e452368be227
Revises: 928a7edc7b35
Create Date: 2024-07-10 02:52:27.320083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e452368be227'
down_revision = '928a7edc7b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')

    # ### end Alembic commands ###
